name: testcontainers requirements
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  requirements:
    strategy:
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Update pip and install pip-tools
        run: pip install --upgrade pip pip-tools
      - name: Build requirements
        run: |
          rm requirements/${{ matrix.python-version }}.txt
          pip-compile --resolver=backtracking -v --upgrade -o requirements/${{ matrix.python-version }}.txt
      - name: Store requirements as artifact
        uses: actions/upload-artifact@v3
        with:
          name: requirements-${{ matrix.python-version }}.txt
          path: requirements/${{ matrix.python-version }}.txt
